language: ruby
rvm:
 - 2.6.5
 - jruby

before_install:
  - gem install bundler

services:
- postgresql
env:
  - database=postgres://postgres@127.0.0.1:5432/propsuite_test

before_script:
  - psql -c 'drop database if exists propsuite_test;' -U postgres
  - psql -c 'create database propsuite_test;' -U postgres

  - from selenium import webdriver
  - from selenium.webdriver.chrome.options import Options
  - options = Options()
  - options.binary_location = "C:\\path\\to\\chrome.exe"
  - options.add_argument("--start-maximized")
  - options.add_argument("--no-sandbox")
  - options.add_argument("--disable-dev-shm-usage")
  - options.add_experimental_option("excludeSwitches", ["enable-automation"])
  - options.add_experimental_option('useAutomationExtension', False)
  - driver = webdriver.Chrome(options=options, executable_path=r'C:\path\to\chromedriver.exe')
  - driver.get('http://google.com/')